---
# Zabbix role default variables

# Version
zabbix_version: "7.0"

# Database - use variables with vault for password
zabbix_db_host: "{{ zabbix_ip | default('192.168.1.113') }}"
zabbix_db_port: 5432
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: "zabbix"  # Change in production - use vault

# Admin account
zabbix_admin_user: "Admin"
zabbix_admin_email: "admin@monitoring.local"
zabbix_admin_password: "zabbix"  # Change in production - use vault

# Frontend settings
zabbix_frontend_user: www-data
zabbix_server_hostname: "{{ zabbix_ip | default('192.168.1.113') }}"
