---
# Zabbix role default variables

# Version
zabbix_version: "7.0"

# Database
zabbix_db_host: localhost
zabbix_db_port: 5432
zabbix_db_name: zabbix
zabbix_db_user: zabbix

# Admin account
zabbix_admin_user: "Admin"
zabbix_admin_email: "admin@localhost"

# Frontend settings
zabbix_frontend_user: www-data
zabbix_server_hostname: localhost
