---
# Prometheus role default variables

# Installation paths
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_home: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus

# Network Configuration
prometheus_ip: "192.168.1.110"
prometheus_port: "9090"

# Retention
prometheus_retention_time: "15d"

# Scrape settings
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

# Exporters
install_node_exporter: true
install_pushgateway: true

# Service targets
alertmanager_targets: []
